# Generated by Django 5.0 on 2024-08-05 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_state_alter_product_category_payment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('PN', 'Paneer'), ('CR', 'Curd'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('ML', 'Milk'), ('CZ', 'Cheese')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Paneer'), ('CR', 'Curd'), ('LS', 'Lassi'), ('GH', 'Ghee'), ('MS', 'Milkshake'), ('IC', 'Ice-Creams'), ('ML', 'Milk'), ('CZ', 'Cheese')], max_length=2),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
